- nuxt_src/components/parts/TheFooter.vue
Resolves: #39 
| Before | After |
|----|----|
| ![Kapture 2019-11-13 at 17 51 55](https://user-images.githubusercontent.com/16359063/68747710-72ae8380-063e-11ea-8d23-866aeb809f29.gif) | ![Kapture 2019-11-13 at 17 50 44](https://user-images.githubusercontent.com/16359063/68747758-878b1700-063e-11ea-87ab-d5095061e125.gif) |
> #39 bug: icon link to top in footer doesn't respect locale.

- nuxt.config.js
- nuxt_src/assets/scss/common/_footer.scss
- nuxt_src/components/parts/flowSns.vue
- nuxt_src/components/parts/snsFooter.vue
- nuxt_src/layouts/default.vue
- nuxt_src/plugins/i18n.js
- nuxt_src/utils/socialMediaUtils.js
このPR はコミット数が多くてSQUASH MERGEでするのおすすめします。
> Tweak flow sns component and facebook share button by locale

- .github/workflows/deploy.yml
- README.md
> Add slack notify step

- nuxt_src/pages/sponsor/index.vue
Resolved: https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/78
> Fix typo "Sponssors"

- nuxt_src/layouts/default.vue
- Fixed to specify full path
Resolved: https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/64
> Fix OGP is not working in tweets

- nuxt.config.js
- package.json
- yarn.lock
Resolved: https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/76
> Google Analytics を追加

- .firebaserc
- .github/workflows/deployStaging.yml
- design_src/htdocs/sponsorship/index.html
- nuxt_src/components/sections/top/banner.vue
- nuxt_src/components/sections/top/mainVisual.vue
- nuxt_src/layouts/default.vue
- nuxt_src/pages/sponsorship/index.vue
> Add deployStaging.yml

- nuxt.config.js
- nuxt_src/assets/scss/common/_header_pc.scss
- nuxt_src/assets/scss/common/_header_sp.scss
- nuxt_src/components/parts/TheHeader.vue
- nuxt_src/pages/login/index.vue
- nuxt_src/plugins/firebase.js
- nuxt_src/store/auth.js
- nuxt_src/store/index.js
- package.json
- yarn.lock
> Login with FirebaseUI

- nuxt_src/components/parts/TheFooter.vue
> #66 uncomment 'Send a pull request' button.

- nuxt_src/assets/scss/top/_top.scss
- nuxt_src/components/sections/top/mainVisual.vue
- ロゴ背景を白色に修正。
- ロゴサイズが均一じゃない場合のレイアウト崩れを修正。
しました。
> Fix syogun logo layout

- nuxt_src/pages/travel/index.vue
👋 Hello, Scala hackers! トラベル情報ページのリンクとかをちょっと直しました 💪
> Fix a few links in the Travel page

- nuxt_src/components/parts/TheHeader.vue
> add proposals link into sp mode menu

- package.json
- yarn.lock
fix npm scripts
add firebase admin
> Upgrade firebase tools

- nuxt_src/components/sections/top/access.vue
| PC | SP |
|-----|-----|
| ![ScalaMatsuri_2020___The_largest_international_Scala_conference_in_Asia](https://user-images.githubusercontent.com/16359063/73463103-0f6ffa00-43c0-11ea-988e-24b02af0d573.png) | ![ScalaMatsuri_2020___The_largest_international_Scala_conference_in_Asia](https://user-images.githubusercontent.com/16359063/73463041-fe26ed80-43bf-11ea-9952-717b5e75928a.png) |
> TOPのGoogle mapを一時的に非表示に

- nuxt_src/pages/sponsorship/index.vue
> 常設ブース完売の知らせを追加

- nuxt_src/components/parts/SessionDetailModal.vue
- nuxt_src/pages/proposals/_id/index.vue
- nuxt_src/plugins/scalaMatsuriCommon.js
- nuxt_src/store/proposals.js
ISSUE: https://github.com/scalamatsuri/2020.scalamatsuri.org/issues/207
プロポーザルの個別ページを作成。
---
> add individual proposal pages

- nuxt_src/components/sections/top/mainVisual.vue
- nuxt_src/pages/cfp/index.vue
- nuxt_src/pages/travel/index.vue
5月となっていた箇所を一律10月に修正しました。
見えない部分が殆どなので、優先度は低めです。
> Fix Schedue Dates

- nuxt_src/pages/sponsorship/index.vue
> 大老のTシャツを-に

- nuxt_src/pages/sponsorship/index.vue
オンライン化に伴いキャンセルが発生したため、再度申し込みを受け付けることにしました。
> バーチャルブースの申し込みを受け付けるように修正

- nuxt_src/components/sections/top/sponsors.vue
fix https://github.com/scalamatsuri/2020.scalamatsuri.org/pull/428#issuecomment-685287076
> fix tairo sponsor duplication

- nuxt_src/pages/sponsors/index.vue
> fix inconsistent roma-ji of tairo-u

- nuxt_src/data/proposals/all.json
- nuxt_src/data/top/acceptedSessions.json
転職により所属先が変わったので、変更をお願いします。
このファイル以外にも修正が必要でしたら教えてください。
> Change my organization

- nuxt_src/data/proposals/all.json
https://github.com/scalamatsuri/2020.scalamatsuri.org/pull/422
の変更漏れ
> change Eugene's organization in proposal detail

- nuxt_src/data/proposals/all.json
- nuxt_src/data/top/acceptedSessions.json
This is the most up-to-date title and description.
> Update title and description of my talk on Caliban

- nuxt_src/components/parts/SessionDetailModal.vue
nuxt.js 初心者ですが、手元で動かした感じでは #355 の問題が解消しているようです。
Fixed #355
> Fixed link to proposal detail

- nuxt_src/components/sections/top/events.vue
消すのは簡単ですが、文字を消すのも寂しいので良い感じに置き換えてみました。
英文のミスとか、こういう文言が良いとか有ればご助言いただきたいです。
| PC | SP |
|-----|-----|
| <img width="1056" alt="ScalaMatsuri_2020___アジア最大級の_Scala_のカンファレンス" src="https://user-images.githubusercontent.com/16359063/94452918-0c493a00-01eb-11eb-941e-17a503e133dc.png"> | <img width="406" alt="ScalaMatsuri_2020___アジア最大級の_Scala_のカンファレンス" src="https://user-images.githubusercontent.com/16359063/94452952-166b3880-01eb-11eb-8fa4-b922ae701f71.png"> |
| <img width="1311" alt="ScalaMatsuri_2020___The_largest_international_Scala_conference_in_Asia" src="https://user-images.githubusercontent.com/16359063/94453071-34d13400-01eb-11eb-8921-1069fc3ff12b.png"> | <img width="407" alt="ScalaMatsuri_2020___The_largest_international_Scala_conference_in_Asia" …
> TOPのイベント文言を修正

- nuxt_src/assets/scss/program/_pc.scss
- nuxt_src/assets/scss/program/_sp.scss
> fix multi speaker layouts in pc and sp

- nuxt_src/data/proposals/all.json
- nuxt_src/data/top/acceptedSessions.json
田所の「Scalaチームのオンボーディング」のセッションに2点の変更を行いました。
- Robert Devlinを登壇者として追加しました
- セッションの説明文を更新しました（日/英）
> Add speaker and update session description of Tadokoro's session

- nuxt_src/components/sections/top/program.vue
- nuxt_src/pages/index.vue
- nuxt_src/pages/program/index.vue
- nuxt_src/pages/unconference/index.vue
- nuxt_src/store/proposals.ts
- nuxt_src/store/sessions.ts
> プログラムへのリンクをTopページへ追加など

- nuxt_src/data/proposals/all.json
- nuxt_src/data/top/acceptedSessions.json
英語チェックを頂いて、題目修正のアドバイスがあったためPRをなげさせていただきます。
> 発表者 竹尾(showmant) の発表題目の修正

- nuxt_src/data/proposals/all.json
- nuxt_src/data/sponsor-sessions/all.json
お世話になっております。
最近TwitterのIDを変更したためScalaMatsruiのページの方も変更お願いしたくPRいたしました。  
また、名前に表記ゆれがあったためそちらも修正しております。
お手数ですがご確認のほどよろしくお願いいたします。
> TwitterのIDを修正: @blac_k_ey -> @nomadblacky

- nuxt_src/pages/code-of-conduct/index.vue
> update harrasment form link

- nuxt_src/data/sessions/all.json
> Chatwork株式会社の前株を後株に修正

- nuxt_src/components/sections/top/banner.vue
- nuxt_src/components/sections/top/thankYou.vue
- nuxt_src/pages/index.vue
> Thank You バナーを設置

- nuxt_src/components/sections/top/thankYou.vue
> Modify some text in thank you

- nuxt_src/components/parts/SessionDetailModal.vue
- nuxt_src/data/sponsor-sessions/all.json
- nuxt_src/data/top/acceptedSessions.json
- nuxt_src/pages/proposals/_id/index.vue
> プログラムのモーダルと詳細画面に、スライドリンクとYoutubeリンクを埋め込む対応

- nuxt_src/components/sections/top/chairpersonRecruit.vue
- nuxt_src/pages/index.vue
- nuxt_src/store/blogPosts.js
> add chairperson recruitement decription to top / update blog category name

- nuxt_src/pages/index.vue
> 座長募集の文言を非表示にした
